name: deploy to production
on:
  release:
    types: [published, edited]
jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo deployment to  production
