name: deploy to production
on:
  push:
    branches: master
jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: dadsad
        env:
          test: 		${{ secrets.TESTSTR}}
        run: echo $test
      - name: ddddddddd
        run: echo  ${{ secrets.TESTSTR}}
