name: deploy to production
on:
  push:
    branches: master
  workflow_dispatch:
    
jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: dadsad
        env:
          test: 		${{ secrets.TESTSTR}}
        run: echo $test
      - name: ddddddddd
        run: echo  ${{ secrets.TESTSTR}}
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: 'npm'
      - name: Install sfdx
        run: npm ci  
      - name: version plugin
        run: npx sfdx plugins --help