name: deploy to production
on:
  push:
    branches: master
  workflow_dispatch:
    
jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: zs
        uses: ./github/workflows/propagation.yml
