name: deploy to production
on:
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: test 
        run: echo version 2 
      